spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autosale2
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    default-property-inclusion: non_null

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true